AllCops:
  Exclude:
    - "bin/*"
    - "db/**/*"
    - "config/**/*"
    - "Guardfile"
    - "Rakefile"
  DisplayCopNames: true

Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Include: ["app/controllers/*"]
  Max: 20
Metrics/AbcSize:
  Include: ["app/controllers/*"]
  Max: 30
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  ExcludedMethods: ['describe']

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

Layout/AlignHash:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Layout/TrailingWhitespace:
  Enabled: false
Layout/Tab:
  Enabled: false
Layout/TrailingBlankLines:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Layout/IndentationConsistency:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/BlockAlignment:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/EmptyLinesAroundMethodBody:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/ClassMethods:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Layout/DefEndAlignment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Layout/SpaceAfterColon: 
  Enabled: false
Layout/ElseAlignment: 
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/GuardClause: 
  Enabled: false
Layout/AccessModifierIndentation:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Style/ColonMethodCall:
  Enabled: false